[doc] Add guide on setting up Thread environment for chip-device-ctrl.py
Damian-Nordic/connectedhomeip pull request #59
Opened 2021-03-11 14:15 UTC by Damian-Nordic

Add an instruction on how to set up a simple testing
environment on Raspberry Pi or other Linux machine to enable
using Python CHIP Controller with Thread devices.

The instruction recommends using nRF52840 Dongle as a Thread
radio device, but can be easily adapted to other radio
solutions.

2021-03-11 16:14 UTC, doublemis1 approved these changes

2021-03-12 07:34 UTC, kkasperczyk-no reviewed
All nice and neat, good job! I have one remark due to discussion about that task on the SD TSG stand-up. You might not have noticed it, but in the stand-up notes, goal of this task is described as to:
* fix the openthread version we standardise on (do not follow openthread master)
* version need to match for RCP

Some folks in the community were happy about our initiative and some were not, as it is some kind of duplication of openthread materials and seems to be not needed by them. It was said that finding some version making everything work together and fixing it would be beneficial for the testing purposes. Do you think we should address it somehow in this PR and for example checkout openthread on some specific revision and describe as supported one?

2021-03-12 11:25 UTC, Damian-Nordic commented
@kkasperczyk-no Given that openthread/otbr Docker images are not versioned I think that we have no choice than following openthread master. In case is causes any issues we can probably host the Docker image in project-chip Dockerhub space, but let's see if CSG requests that.

2021-03-12 11:34 UTC, kkasperczyk-no approved these changes

2021-03-15 09:11 UTC, greg-fer approved these changes

2021-03-15 14:25 UTC, greg-fer requested changes
Sorry, need to have another look.

2021-03-15 14:38 UTC, greg-fer approved these changes

2021-05-20 19:37 UTC, closed without merging